/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as ApiAttackDefensePlanRouteImport } from './routes/api/attack-defense-plan'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiCheckDomainTrustRouteImport } from './routes/api/check-domain-trust'
import { Route as ApiCheckLinkRouteImport } from './routes/api/check-link'
import { Route as ApiDeleteAccountRouteImport } from './routes/api/delete-account'
import { Route as ApiTextToSpeechRouteImport } from './routes/api/text-to-speech'
import { Route as CoursesCourseSlugRouteImport } from './routes/courses_.$courseSlug'
import { Route as ToolsSlugRouteImport } from './routes/tools_.$slug'
import { Route as TopicSlugRouteImport } from './routes/topic.$slug'
import { Route as VerifyCertIdRouteImport } from './routes/verify.$certId'
import { Route as CoursesCourseSlugLessonIdRouteImport } from './routes/courses_.$courseSlug_.$lessonId'
import { Route as CoursesCourseSlugFinalExamRouteImport } from './routes/courses_.$courseSlug_.final-exam'
import { Route as CoursesCourseSlugUnitExamUnitIdRouteImport } from './routes/courses_.$courseSlug_.unit-exam.$unitId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAttackDefensePlanRoute = ApiAttackDefensePlanRouteImport.update({
  id: '/api/attack-defense-plan',
  path: '/api/attack-defense-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckDomainTrustRoute = ApiCheckDomainTrustRouteImport.update({
  id: '/api/check-domain-trust',
  path: '/api/check-domain-trust',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckLinkRoute = ApiCheckLinkRouteImport.update({
  id: '/api/check-link',
  path: '/api/check-link',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeleteAccountRoute = ApiDeleteAccountRouteImport.update({
  id: '/api/delete-account',
  path: '/api/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTextToSpeechRoute = ApiTextToSpeechRouteImport.update({
  id: '/api/text-to-speech',
  path: '/api/text-to-speech',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseSlugRoute = CoursesCourseSlugRouteImport.update({
  id: '/courses_/$courseSlug',
  path: '/courses/$courseSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSlugRoute = ToolsSlugRouteImport.update({
  id: '/tools_/$slug',
  path: '/tools/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicSlugRoute = TopicSlugRouteImport.update({
  id: '/topic/$slug',
  path: '/topic/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyCertIdRoute = VerifyCertIdRouteImport.update({
  id: '/verify/$certId',
  path: '/verify/$certId',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseSlugLessonIdRoute =
  CoursesCourseSlugLessonIdRouteImport.update({
    id: '/courses_/$courseSlug_/$lessonId',
    path: '/courses/$courseSlug/$lessonId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CoursesCourseSlugFinalExamRoute =
  CoursesCourseSlugFinalExamRouteImport.update({
    id: '/courses_/$courseSlug_/final-exam',
    path: '/courses/$courseSlug/final-exam',
    getParentRoute: () => rootRouteImport,
  } as any)
const CoursesCourseSlugUnitExamUnitIdRoute =
  CoursesCourseSlugUnitExamUnitIdRouteImport.update({
    id: '/courses_/$courseSlug_/unit-exam/$unitId',
    path: '/courses/$courseSlug/unit-exam/$unitId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tools': typeof ToolsRoute
  '/api/attack-defense-plan': typeof ApiAttackDefensePlanRoute
  '/api/chat': typeof ApiChatRoute
  '/api/check-domain-trust': typeof ApiCheckDomainTrustRoute
  '/api/check-link': typeof ApiCheckLinkRoute
  '/api/delete-account': typeof ApiDeleteAccountRoute
  '/api/text-to-speech': typeof ApiTextToSpeechRoute
  '/courses/$courseSlug': typeof CoursesCourseSlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/topic/$slug': typeof TopicSlugRoute
  '/verify/$certId': typeof VerifyCertIdRoute
  '/courses/$courseSlug/$lessonId': typeof CoursesCourseSlugLessonIdRoute
  '/courses/$courseSlug/final-exam': typeof CoursesCourseSlugFinalExamRoute
  '/courses/$courseSlug/unit-exam/$unitId': typeof CoursesCourseSlugUnitExamUnitIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tools': typeof ToolsRoute
  '/api/attack-defense-plan': typeof ApiAttackDefensePlanRoute
  '/api/chat': typeof ApiChatRoute
  '/api/check-domain-trust': typeof ApiCheckDomainTrustRoute
  '/api/check-link': typeof ApiCheckLinkRoute
  '/api/delete-account': typeof ApiDeleteAccountRoute
  '/api/text-to-speech': typeof ApiTextToSpeechRoute
  '/courses/$courseSlug': typeof CoursesCourseSlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/topic/$slug': typeof TopicSlugRoute
  '/verify/$certId': typeof VerifyCertIdRoute
  '/courses/$courseSlug/$lessonId': typeof CoursesCourseSlugLessonIdRoute
  '/courses/$courseSlug/final-exam': typeof CoursesCourseSlugFinalExamRoute
  '/courses/$courseSlug/unit-exam/$unitId': typeof CoursesCourseSlugUnitExamUnitIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tools': typeof ToolsRoute
  '/api/attack-defense-plan': typeof ApiAttackDefensePlanRoute
  '/api/chat': typeof ApiChatRoute
  '/api/check-domain-trust': typeof ApiCheckDomainTrustRoute
  '/api/check-link': typeof ApiCheckLinkRoute
  '/api/delete-account': typeof ApiDeleteAccountRoute
  '/api/text-to-speech': typeof ApiTextToSpeechRoute
  '/courses_/$courseSlug': typeof CoursesCourseSlugRoute
  '/tools_/$slug': typeof ToolsSlugRoute
  '/topic/$slug': typeof TopicSlugRoute
  '/verify/$certId': typeof VerifyCertIdRoute
  '/courses_/$courseSlug_/$lessonId': typeof CoursesCourseSlugLessonIdRoute
  '/courses_/$courseSlug_/final-exam': typeof CoursesCourseSlugFinalExamRoute
  '/courses_/$courseSlug_/unit-exam/$unitId': typeof CoursesCourseSlugUnitExamUnitIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/auth'
    | '/courses'
    | '/dashboard'
    | '/sitemap.xml'
    | '/tools'
    | '/api/attack-defense-plan'
    | '/api/chat'
    | '/api/check-domain-trust'
    | '/api/check-link'
    | '/api/delete-account'
    | '/api/text-to-speech'
    | '/courses/$courseSlug'
    | '/tools/$slug'
    | '/topic/$slug'
    | '/verify/$certId'
    | '/courses/$courseSlug/$lessonId'
    | '/courses/$courseSlug/final-exam'
    | '/courses/$courseSlug/unit-exam/$unitId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auth'
    | '/courses'
    | '/dashboard'
    | '/sitemap.xml'
    | '/tools'
    | '/api/attack-defense-plan'
    | '/api/chat'
    | '/api/check-domain-trust'
    | '/api/check-link'
    | '/api/delete-account'
    | '/api/text-to-speech'
    | '/courses/$courseSlug'
    | '/tools/$slug'
    | '/topic/$slug'
    | '/verify/$certId'
    | '/courses/$courseSlug/$lessonId'
    | '/courses/$courseSlug/final-exam'
    | '/courses/$courseSlug/unit-exam/$unitId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/auth'
    | '/courses'
    | '/dashboard'
    | '/sitemap.xml'
    | '/tools'
    | '/api/attack-defense-plan'
    | '/api/chat'
    | '/api/check-domain-trust'
    | '/api/check-link'
    | '/api/delete-account'
    | '/api/text-to-speech'
    | '/courses_/$courseSlug'
    | '/tools_/$slug'
    | '/topic/$slug'
    | '/verify/$certId'
    | '/courses_/$courseSlug_/$lessonId'
    | '/courses_/$courseSlug_/final-exam'
    | '/courses_/$courseSlug_/unit-exam/$unitId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AuthRoute: typeof AuthRoute
  CoursesRoute: typeof CoursesRoute
  DashboardRoute: typeof DashboardRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ToolsRoute: typeof ToolsRoute
  ApiAttackDefensePlanRoute: typeof ApiAttackDefensePlanRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiCheckDomainTrustRoute: typeof ApiCheckDomainTrustRoute
  ApiCheckLinkRoute: typeof ApiCheckLinkRoute
  ApiDeleteAccountRoute: typeof ApiDeleteAccountRoute
  ApiTextToSpeechRoute: typeof ApiTextToSpeechRoute
  CoursesCourseSlugRoute: typeof CoursesCourseSlugRoute
  ToolsSlugRoute: typeof ToolsSlugRoute
  TopicSlugRoute: typeof TopicSlugRoute
  VerifyCertIdRoute: typeof VerifyCertIdRoute
  CoursesCourseSlugLessonIdRoute: typeof CoursesCourseSlugLessonIdRoute
  CoursesCourseSlugFinalExamRoute: typeof CoursesCourseSlugFinalExamRoute
  CoursesCourseSlugUnitExamUnitIdRoute: typeof CoursesCourseSlugUnitExamUnitIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/attack-defense-plan': {
      id: '/api/attack-defense-plan'
      path: '/api/attack-defense-plan'
      fullPath: '/api/attack-defense-plan'
      preLoaderRoute: typeof ApiAttackDefensePlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/check-domain-trust': {
      id: '/api/check-domain-trust'
      path: '/api/check-domain-trust'
      fullPath: '/api/check-domain-trust'
      preLoaderRoute: typeof ApiCheckDomainTrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/check-link': {
      id: '/api/check-link'
      path: '/api/check-link'
      fullPath: '/api/check-link'
      preLoaderRoute: typeof ApiCheckLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/delete-account': {
      id: '/api/delete-account'
      path: '/api/delete-account'
      fullPath: '/api/delete-account'
      preLoaderRoute: typeof ApiDeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/text-to-speech': {
      id: '/api/text-to-speech'
      path: '/api/text-to-speech'
      fullPath: '/api/text-to-speech'
      preLoaderRoute: typeof ApiTextToSpeechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses_/$courseSlug': {
      id: '/courses_/$courseSlug'
      path: '/courses/$courseSlug'
      fullPath: '/courses/$courseSlug'
      preLoaderRoute: typeof CoursesCourseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools_/$slug': {
      id: '/tools_/$slug'
      path: '/tools/$slug'
      fullPath: '/tools/$slug'
      preLoaderRoute: typeof ToolsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topic/$slug': {
      id: '/topic/$slug'
      path: '/topic/$slug'
      fullPath: '/topic/$slug'
      preLoaderRoute: typeof TopicSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$certId': {
      id: '/verify/$certId'
      path: '/verify/$certId'
      fullPath: '/verify/$certId'
      preLoaderRoute: typeof VerifyCertIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses_/$courseSlug_/$lessonId': {
      id: '/courses_/$courseSlug_/$lessonId'
      path: '/courses/$courseSlug/$lessonId'
      fullPath: '/courses/$courseSlug/$lessonId'
      preLoaderRoute: typeof CoursesCourseSlugLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses_/$courseSlug_/final-exam': {
      id: '/courses_/$courseSlug_/final-exam'
      path: '/courses/$courseSlug/final-exam'
      fullPath: '/courses/$courseSlug/final-exam'
      preLoaderRoute: typeof CoursesCourseSlugFinalExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses_/$courseSlug_/unit-exam/$unitId': {
      id: '/courses_/$courseSlug_/unit-exam/$unitId'
      path: '/courses/$courseSlug/unit-exam/$unitId'
      fullPath: '/courses/$courseSlug/unit-exam/$unitId'
      preLoaderRoute: typeof CoursesCourseSlugUnitExamUnitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AuthRoute: AuthRoute,
  CoursesRoute: CoursesRoute,
  DashboardRoute: DashboardRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ToolsRoute: ToolsRoute,
  ApiAttackDefensePlanRoute: ApiAttackDefensePlanRoute,
  ApiChatRoute: ApiChatRoute,
  ApiCheckDomainTrustRoute: ApiCheckDomainTrustRoute,
  ApiCheckLinkRoute: ApiCheckLinkRoute,
  ApiDeleteAccountRoute: ApiDeleteAccountRoute,
  ApiTextToSpeechRoute: ApiTextToSpeechRoute,
  CoursesCourseSlugRoute: CoursesCourseSlugRoute,
  ToolsSlugRoute: ToolsSlugRoute,
  TopicSlugRoute: TopicSlugRoute,
  VerifyCertIdRoute: VerifyCertIdRoute,
  CoursesCourseSlugLessonIdRoute: CoursesCourseSlugLessonIdRoute,
  CoursesCourseSlugFinalExamRoute: CoursesCourseSlugFinalExamRoute,
  CoursesCourseSlugUnitExamUnitIdRoute: CoursesCourseSlugUnitExamUnitIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
